//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehiculos_ITM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public int Agencia { get; set; }
        public int Cliente { get; set; }
        public int Vehiculo { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Agencia Agencia1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
