//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehiculos_ITM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public int Agencia { get; set; }
        public int Cliente { get; set; }
        public int Vehiculo { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Agencia Agencia1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
